version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - info_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=database1_role
      - POSTGRES_PASSWORD=database1_password
      - POSTGRES_DB=moviecatalogdb
    container_name: db
    ports:
      - 5432:5432
  db2:
    image: postgres:12.0-alpine
    volumes:
      - catalog_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=database1_role
      - POSTGRES_PASSWORD=database1_password
      - POSTGRES_DB=movieinfodb
    container_name: db2
    ports:
      - 5433:5432





volumes:
  info_volume:
  catalog_volume:
