INSERT INTO team (id,name, city,abrv) VALUES
    (1, 'Hawks', 'Atlanta', 'ATL'),
    (2,'Nets', 'Brooklyn', 'BKN'),
    (3, 'Celtics','Boston','BOS'),
    (4, 'Hornets','Charllote','CHA'),
    (5, 'Bulls','Chicago','CHI'),
    (6, 'Cavaliers','Cleveland','CLE'),
    (7, 'Mavericks','Dallas','DAL'),
    (8, 'Nuggets','Denver','DEN'),
    (9, 'Pistons','Detroit','DET'),
    (10, 'Warriors','Golden State','GSW'),
    (11, 'Rockets','Houston','HOU'),
    (12, 'Pacers','Indiana','Pacers'),
    (13, 'Clippers','Los Angeles','LAC'),
    (14, 'Lakers','Los Angeles','LAL'),
    (15, 'Grizzlies','Memphis','MEM'),
    (16, 'Heat','Miami','MIA'),
    (17, 'Bucks','Milwaukee','MIL'),
    (18, 'Pelicans','New Orleans','NOP'),
    (19, 'Knicks','New York','NYK'),
    (20, 'Thunder','Oklahoma City','OKC'),
    (21, 'Magic','Orlando','ORL'),
    (22, '76ers','Philadelphia','PHI'),
    (23, 'Suns','Phoenix','PHX'),
    (24, 'Trail Blazers','Portland','POR'),
    (25, 'Kings','Sacremento','SAC'),
    (26, 'Spurs','San Antonio','SAS'),
    (27, 'Jazz','Utah','UTA'),
    (28, 'Wizards','Washington','WAS'),
    (29, 'Timberwolves','Minnesota','MIN'),
    (30, 'Raptors','Toronto','RAPTORS');

    ;